version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - web_logs:/var/log/web

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql

volumes:
  db_data:
  web_logs:
  db_logs:
