version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: # nick-vdm-dev/backend:latest
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - backend_data:/code/files
    networks:
      - app-network

  frontend:
    image: # nick-vdm-dev/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    environment:
      BACKEND_URL: ${BACKEND_URL}
    networks:
      - app-network

volumes:
  postgres_data:
  backend_data:

networks:
  app-network:
